version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo_local
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    restart: 'no'

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: nest_api
    command: npm run start:dev
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/nest_auth
      - MONGODB_DBNAME=nest_auth
      - JWT_SECRET=please_change_me
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    restart: 'no'

volumes:
  mongo_data:
